### ISSUE TITLE
Peer-to-Peer code review

### ISSUE THREAD

**Issue by BereketRetta** [myelin0/Leaderboard#5]
Great Job on your Project👏

You met all the requirements and you have done a good job implementing the ES6 Syntax.
But you need to update your readme with a demo link
All linters are passing ✔️
Good commit history ✔️
Good PR description ✔️
Good README description✔
Your design looks perfect 💯 👍 ✔️

**Comment by myelin0** [comment]
Thanks ! I will deploy it asap.
